// cute_parser.bison.y

/*
MIT License

Copyright (c) 2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// bison -Wall -Wdangling-alias -Werror --color=always -Wcounterexamples --report=counterexamples,lookaheads --report-file=bisonreport.txt cute_parser.bison.y

// c++ parser classes skeleton file
%skeleton "lalr1.cc"

%require "3.8"

// c++ parser
%language "c++"

// generate parser description report .output file
%verbose

%defines "cute_parser.bison.h"
%output "cute_parser.bison.cpp"

// enable debug trace
%define parse.trace

// adds location parameter to symbol constructors
%locations

// generate header for location to be used outside of bison parser
%define api.location.file "locations.bison.h"

%define parse.error detailed

// want to return character token from flex but don't think it can work with api.token.constructor
// better lookup performance at cost of disallowing literal characters in grammar
%define api.token.raw

%code requires {
// %code requires codeblock goes at top of .h outside of namespace and parser class
// standard c++ #includes and defines

#include <string>
#include <functional>
#include <chrono>
#include <print>

#include "locations.bison.h"

namespace cuteparser {

using namespace std;
using namespace chrono;

struct Context {
};

struct BisonParam {
  Context context{};
  struct Stats {
    time_point<steady_clock> parseStartTime;
    time_point<steady_clock> parseEndTime;
    duration<double> parseTimeSec;
  } stats{};

};

// info for lexer to use in yylex
struct LexParam {
// position in input stream for lexer to update
  location loc{};

// lexical feedback callbacks, override these in tests as needed

// return count of arguments expected for operation or option
  function<int(const string&)> get_arg_count{};
};

}

// println formatter for location object
template<>
struct std::formatter<cuteparser::location> {
  std::format_context::iterator format(const cuteparser::location& loc, std::format_context& ctx) const {
    std::ostringstream os;
    os << loc;
    return std::format_to(ctx.out(), "{}", os.str());
  }

  constexpr std::format_parse_context::const_iterator parse(std::format_parse_context& ctx) const {
    return ctx.begin();
  }

};

}

// custom namespace generated by bison
%define api.namespace {cuteparser}

// custom classname generated by bison
%define api.parser.class {CuteParser}

// parser constructor parameter 1
// this is the yylex bison will call, it can have any signature we want since it's a lambda passed in by the client that wraps and hides the actual yylex call
%parse-param {function<CuteParser::symbol_type(LexParam&)> yylex}

// parser constructor parameter 2
%parse-param {BisonParam& bisonParam}

// parser constructor parameter 3
// only because each lex-param also must be parse-param
%parse-param {LexParam& lexParam}

// yylex parameter 1
// pass location and lexical feedback info to lexer
%lex-param {LexParam& lexParam}

// use actual types for tokens
%define api.value.type variant

// use c++ objects, changes signature of yylex, yylex now returns PGNParser::symbol_type, yylex takes no parameters, change everywhere yylex is referenced, eg parse-param, any lambdas
%define api.token.constructor

%define parse.assert

%code provides {
// %code provides codeblock goes in .h after namespace and parser class
// everything here needs CuteParser defined earlier

// parser objects
namespace cuteparser {

using namespace std;

}

}

%{
// %{ unnamed codeblock goes at very top of .cpp file before namespace and parser class

#include <sstream>

%}

%code {
// %code codeblock goes at top of .cpp outside namespace and parser class

#include <chrono>
#include <print>

using namespace std;

namespace {
  const string defaultInputName = "inputstream"s;
}

void cuteparser::CuteParser::error(const location& loc, const string& msg) {
  println("error at {}: {}", loc, msg);

}

}

%initial-action {
// %initial-action codeblock goes inside parse() function in .cpp, it's a separate brace-scoped block, anything declared here is local to this block and cannot be used anywhere else in parse()

// suppress unused variable warning till fix in release after version 3.8.2, https://github.com/akimd/bison/commit/a166d5450e3f47587b98f6005f9f5627dbe21a5b
// yynerrs_ is local to generated parse function
  (void)yynerrs_;

  bisonParam.stats.parseStartTime = steady_clock::now();

  auto& loc = lexParam.loc;

  if(loc.begin.filename == nullptr) {
    loc.initialize(&defaultInputName);
  }

// define callbacks for lexer to use for lexical feedback
  if(!lexParam.get_arg_count) {
    lexParam.get_arg_count = [&context = bisonParam.context](const string&) -> int {
      return 0;
    };
  }

}

%token COMMA                ","
%token DASH_DASH            "--"
%token SEMICOLON            ";"

// virtual split token for lexer to signal end of args using lexical feedback
%token ARG_END

%token <string> STRING
%token <string> IDENTIFIER
%token <string> O_NAME


%start script

%%

// no code allowed in rules section, just bison comments that are dropped from .cpp

script: statements postprocess

statements: statement | statements statement | statements ";" statement

statement: mutation

operations: operation | operations operation

operation: "--" op_name arg_list ARG_END

op_name: O_NAME

arg_list: %empty | arg | arg_list "," arg

arg: STRING | IDENTIFIER

mutation: object | object operations

object: IDENTIFIER | STRING

// midrule action for postprocessing
postprocess: %empty {
  auto& [start, end, elapsed] = bisonParam.stats;
  end = steady_clock::now();
  elapsed = end - start;
}

%%

#ifdef BUILD_BISON_MAIN

#include <stdlib.h>
#include <stdio.h>
#include <getopt.h>

#include <string>
#include <iostream>
#include <memory>
#include <istream>
#include <fstream>
#include <print>

#include "lexer/cute_lexer.h"
#include "cute_parser.bison.h"

using namespace std;
using namespace cuteparser;

void usage() {
  puts("Usage: cuteparse [-h | --help] [--debug] [--stats] [file]");
  puts("Parses CUTE script from file or stdin");
  puts("Prints nothing if parse succeeds, otherwise prints an error message with line number");
  puts("");
  puts("Options:");
  puts("--debug: turn on Bison parser and Flex lexer debug traces, off by default");
  puts("--stats: print timing stats on successful parse, off by default");
  puts("--help | -h: print usage help");
  puts("file: CUTE script to read and parse, use stdin if no file or file is \"-\"");
}

int main(int argc, char* argv[])
{
  bool debug{};
  bool printStats{};

// need filename pointer to stick around for bison error messages that print filename and position
  auto inputFilename = make_unique<string>("stdin");
  string changefile;

  option opts[] = {
    {"debug", no_argument, (int*)&debug, 1},
    {"stats", no_argument, (int*)&printStats, 1},
    {"help", no_argument, 0, 'h'},
    {0, 0, 0, 0}
  };

  for(int i, optLetter; (optLetter = getopt_long(argc, argv, "h", opts, &i)) != -1;) {
    switch(optLetter) {
    case 0:
      break;
    case 'h':
      usage();
      return 0;
    case '?':
      usage();
      return 1;
    default:
      break;
    }
  }

  Lexer lexer;

// set filename for bison error reporting
// switch input stream for lexer to read from file instead of default stdin
  ifstream fileStream;
  if(optind < argc) {
    auto file = argv[optind];
    if(file != "-"sv) {
      if(fileStream.open(file); !fileStream) {
        println(stderr, "error opening file \"{}\"", file);
        exit(1);
      }
    }
    *inputFilename = file;
    lexer.switch_streams(&fileStream);
  }

  BisonParam bisonParam;
  LexParam lexParam{.loc = location(inputFilename.get())};

  duration<double> yylexSecs{};

  CuteParser parser([&lexer, &yylexSecs](LexParam& lexParam) -> CuteParser::symbol_type {
    time_point<steady_clock> start = steady_clock::now();
    auto token = lexer.yylex(lexParam);
    time_point<steady_clock> end = steady_clock::now();
    yylexSecs += end - start;
    return token;
  },
  bisonParam,
  lexParam);


  lexer.set_debug(debug);
  parser.set_debug_level(debug);

  if(auto ev = parser(); ev != 0) {
    fputs("parse failed\n", stderr);
    return ev;
  }

  if(printStats) {
    const auto& [_, _, parseSecs] = bisonParam.stats;
    println("parse time: {:.9f} secs", parseSecs.count());
    println("lex_time {:.9f} sec", yylexSecs.count());
  }

  return 0;
}

#endif

