#ifndef CUTE_LEXER_H
#define CUTE_LEXER_H
// cute_lexer.h

/*
MIT License

Copyright (c) 2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include "cute_parser.bison.h"

#include "cute_lexer_guard.h"

namespace cuteparser {
using namespace std;

class Lexer: public yyFlexLexer {
public:

// this is not yylex generated by flex - that yylex is a private function below called yylexGen
// this yylex is a simple wrapper for yylexGen
  CuteParser::symbol_type yylex(LexParam& param) {
    auto token = yylexGen(param);
    return checkToken(token);
  }

  Lexer() = default;

  explicit Lexer(istream* yyin_arg): yyFlexLexer(yyin_arg) {}
  explicit Lexer(istream& yyin_arg): yyFlexLexer(&yyin_arg) {}

private:

// this is the real yylex generated by flex
// can only declare here since flex generates the implementation
  CuteParser::symbol_type yylexGen(LexParam&);

// fix gcc-13 warning -Woverloaded-virtual that virtual int CuteFlexLexer::yylex() was hidden
  using yyFlexLexer::yylex;

private:
// member variables for data needed across yylex calls

// these states could be implemented as flex start condition states
// but I think it's nicer this way since there's no pattern matching involved
// and they're really meant for logic before or after a token is matched

  enum class lexer_state {
    normal,
    opStart,
    argList,
    argEnd,
  } lexer_state = lexer_state::normal;

  string oName;
  int numArgLeft{};

private:

  CuteParser::symbol_type checkToken(const CuteParser::symbol_type& token) {

    using symbol_kind = CuteParser::symbol_kind;
    constexpr auto S_O_NAME = symbol_kind::S_O_NAME;
    constexpr auto S_IDENTIFIER = symbol_kind::S_IDENTIFIER;
    constexpr auto S_STRING = symbol_kind::S_STRING;

    constexpr auto normal = lexer_state::normal;
    constexpr auto opStart = lexer_state::opStart;
    constexpr auto argList = lexer_state::argList;
    constexpr auto argEnd = lexer_state::argEnd;

    switch(lexer_state) {
    case normal:
      if(token.kind() == S_O_NAME) {
        oName = token.value.as<string>();
        lexer_state = opStart;
      }
      return token;

    case argList:
      if(token.kind() == S_IDENTIFIER || token.kind() == S_STRING) {
        --numArgLeft;
      }
      if(numArgLeft == 0) {
        lexer_state = argEnd;
      }
      return token;

    default:
      break;
    }

    throw CuteParser::syntax_error(token.location, "unexpected combination of lexer_state "s + to_string((int)lexer_state) + " and token " + to_string(token.kind()));
  }
  

};

}

#endif


